import { Geist, Geist_Mono } from "next/font/google";

// import "./globals.css";
import "./styles/globals.css";
import Footer from "./(components)/Footer";
import Navbar from "./(components)/Navbar";
import { Provider } from "react-redux";
import { store } from "../reduxStore";
import ReduxProvider from "./ReduxProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-auto`}
      >
        <ToastContainer position="top-right" autoClose={3000} />
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
